language: minimal

services:
  - docker

env:
  - DOCKER_REPO=quay.io/aboutsource/ruby RUBY_VERSION=2.5

script:
  - |
    docker build \
      --file $RUBY_VERSION/Dockerfile \
      --tag $DOCKER_REPO:$RUBY_VERSION \
      --build-arg BUILD_ID=$TRAVIS_BUILD_ID \
      $RUBY_VERSION/

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io

deploy:
  - provider: script
    script: docker push $DOCKER_REPO:$RUBY_VERSION
    on:
      branch: master
